### ISSUE TITLE
Cannot start Genie REPL

### ISSUE THREAD

**Issue by flibe** [essenciary/Genie.jl#121]
Hello, I am new to Genie and I am trying to replicate the tutorials. 
I have an issue when creating apps: Genie REPL does not start and repl.bat and server.bat seem to be broken.

**versioninfo()**
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
```

When I run 
`julia> Genie.REPL.new_app("your_cool_new_app")`

the app is created and working at http://localhost:8000/.

![image](https://user-images.githubusercontent.com/13964260/53372285-bba89580-3952-11e9-99b1-39902061a00b.png)

However, Genie REPL is not loaded and I cannot start it via repl.bat, which appears broken (same for server.bat).

![image](https://user-images.githubusercontent.com/13964260/53372510-5608d900-3953-11e9-84c8-c24e1b71b5fc.png)

Thank you for any help! Maybe this is the same issue as #115.
Best
Francesco

**Comment by essenciary** [comment]
@flibe Ah sorry, it's due to some recent changes. I pushed a fix. 
Can you update to latest Genie (0.8.7) and try again (create the app from scratch). 
Should be fine now (the problem was the the .bat files were referencing `bootstrap.jl` instead of `../bootstrap.jl` (one folder up): 
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/11292378/53373882-0af0c500-3957-11e9-9de1-645eb0779801.png">

**Comment by flibe** [comment]
Thank you, both repl.bat and server.bat work now.

One residual doubt I have is that when I run repl.bat it seems I still get the Julia REPL. 
I would need to access Genie REPL instead, to be able to run command
`genie> Genie.REPL.new_controller("Books")`
Thank you
Best
Francesco

**repl.bat**
![image](https://user-images.githubusercontent.com/13964260/53375001-59539300-395a-11e9-9516-a3c217a1b29c.png)

**From Julia REPL**
![image](https://user-images.githubusercontent.com/13964260/53375466-a5530780-395b-11e9-8436-2349d920c2e1.png)

**Comment by essenciary** [comment]
@flibe Once you run `repl.bat` both the app and the Genie code is loaded. You don't need to run `Genie.REPL.load_app()`

In more recent changes I have removed the `genie>` cursor to speed up Genie (it required an extra dependency). 

I will have to update the README to reflect that. But the point is, the app is fully loaded after `repl.bat`.

**Comment by flibe** [comment]
Thank you very much, I would like to ask 2 additional questions:

1 - Following the docs, I have now generated the app but I fail to generate a Controller:

![image](https://user-images.githubusercontent.com/13964260/53702983-d70d1800-3e0c-11e9-9e7d-bbe893c87f0a.png)


2 - I have built a simple REST server in Julia, using Genie. I would like to reduce latency as much as possible: is there a way to put Genie in a silent mode, in which nothing is printed to screen by Genie when the service is called?

Thank you
Best
Francesco
